import {
  pgTable,
  uniqueIndex,
  text,
  timestamp,
  numeric,
  boolean,
  bigint,
  jsonb,
} from 'drizzle-orm/pg-core';

export const creditLedgerEntryEvent = pgTable(
  'credit_ledger_entry_event',
  {
    id: text().primaryKey().notNull(),
    updated_at: timestamp({ withTimezone: true, mode: 'string' }),
    amount: numeric({ precision: 38, scale: 19 }),
    block_expiry_date: timestamp({ withTimezone: true, mode: 'string' }),
    block_id: text(),
    cost_basis: numeric({ precision: 38, scale: 19 }),
    currency: text(),
    customer_id: text(),
    deleted_at: timestamp({ withTimezone: true, mode: 'string' }),
    description: text(),
    ending_balance: numeric({ precision: 38, scale: 19 }),
    entry_status: text(),
    entry_type: text().notNull(),
    invoice_id: text(),
    invoice_line_item_id: text(),
    is_revert: boolean(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    ledger_sequence_number: bigint({ mode: 'number' }),
    lock_adjusted_timestamp: timestamp({
      withTimezone: true,
      mode: 'string',
    }),
    metadata: jsonb(),
    new_block_expiry_date: timestamp({ withTimezone: true, mode: 'string' }),
    price_id: text(),
    recognized_revenue_amount: numeric({ precision: 38, scale: 19 }),
    source_id: text(),
    starting_balance: numeric({ precision: 38, scale: 19 }),
    timestamp: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
    void_amount: numeric({ precision: 38, scale: 19 }),
    void_reason: text(),
    created_at: timestamp({ withTimezone: true, mode: 'string' }),
  },
  table => [
    uniqueIndex('idx_credit_ledger_entry_event_primary_key').using(
      'btree',
      table.id.asc().nullsLast().op('text_ops')
    ),
  ]
);

export const invoice = pgTable('invoice', {
  id: text().primaryKey().notNull(),
  updated_at: timestamp({ withTimezone: true, mode: 'string' }),
  metadata: jsonb(),
  amount_due: numeric({ precision: 38, scale: 2 }),
  created_at: timestamp({ withTimezone: true, mode: 'string' }),
  currency: text(),
  customer: jsonb(),
  discount: numeric({ precision: 38, scale: 2 }),
  discounts: jsonb(),
  due_date: timestamp({ withTimezone: true, mode: 'string' }),
  invoice_pdf: text(),
  invoice_number: text(),
  minimum: numeric({ precision: 38, scale: 2 }),
  minimum_amount: numeric({ precision: 38, scale: 2 }),
  maximum: numeric({ precision: 38, scale: 2 }),
  maximum_amount: numeric({ precision: 38, scale: 2 }),
  line_items: jsonb(),
  subscription: text(),
  subtotal: numeric({ precision: 38, scale: 2 }),
  total: numeric({ precision: 38, scale: 2 }),
  customer_balance_transactions: jsonb(),
  status: text(),
  invoice_source: text(),
  shipping_address: jsonb(),
  billing_address: jsonb(),
  hosted_invoice_url: text(),
  will_auto_issue: boolean(),
  eligible_to_issue_at: timestamp({ withTimezone: true, mode: 'string' }),
  customer_tax_id: text(),
  voided_at: timestamp({ withTimezone: true, mode: 'string' }),
  paid_at: timestamp({ withTimezone: true, mode: 'string' }),
  issued_at: timestamp({ withTimezone: true, mode: 'string' }),
  scheduled_issue_at: timestamp({ withTimezone: true, mode: 'string' }),
  auto_collection: jsonb(),
  memo: text(),
  issue_failed_at: timestamp({ withTimezone: true, mode: 'string' }),
  sync_failed_at: timestamp({ withTimezone: true, mode: 'string' }),
  payment_failed_at: timestamp({ withTimezone: true, mode: 'string' }),
  payment_started_at: timestamp({ withTimezone: true, mode: 'string' }),
  credit_notes: jsonb(),
  invoice_date: timestamp({ withTimezone: true, mode: 'string' }),
});
