name: Secret Scanning

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  trufflehog:
    runs-on: ${{ vars.RUNNER_DEFAULT_LABEL || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@v3.93.0
        with:
          extra_args: --results=verified,unknown
